#!/usr/bin/env python3
"""Fail if a committed file attributes org governance to an automation agent.

Org policy (tuna-os/.github#54): governance and process documents must be
attributable to a named human or team. A document that names an automation
agent as its author or owner, or that carries an ACMM-level byline, reads as
unowned -- a newcomer opens RFC-PROCESS.md or TRIAGE-POLICY.md and finds a
process nobody stands behind.

That text propagates. The project-starter ROADMAP template used to ship it, and
every repository scaffolded from it inherited it -- 37 committed files across
19 repositories, including the org versioning, triage, RFC and ADR documents.
PR #55 stripped the byline from the template and from this repository's own
ROADMAP.md. This check is what keeps it from coming back: it fails a commit or
PR that reintroduces either signal, so a regenerated byline is caught at the
source (this repo ships both the template and the roadmap it is copied from)
rather than having to be swept out of 19 repos again.

Two signals, both of which name an agent or an ACMM level in a way that cannot
be audited and reads as authorship:

  1. An ACMM level reference -- "ACMM L6", "acmm l0". These are agent-capability
     metadata. They belong in issue and PR bodies and in DCO commit trailers,
     where they are attached to a specific change -- never baked into a
     committed document's content.

  2. An authorship/ownership attribution to an agent -- the shape
     "by the <role> agent" / "by <role> agent", which also matches the exact
     offending sentences ("This roadmap is maintained by the strategist agent",
     "Generated by strategist agent at ACMM L6"). The preposition "by" is the
     signal that an agent is named as author/owner, rather than merely
     mentioned as a category.

The check is deliberately narrow, not a natural-language authorship detector.
"human or agent", "automated agents (hive)", "User-Agent", "agent-authored",
"agent guide" are all legitimate and must pass. Requiring an ACMM level, or an
authorship preposition before the role+agent, keeps those clean. For a gate
whose whole point is catching a byline that silently returns, a narrow pattern
that pins the exact regression shape is correct; a too-broad one would flag
every document that mentions agents, get switched off, and then nothing would
be checked at all.

Usage:
    check-agent-byline.py

Exit codes:
    0  compliant (no committed file is flagged)
    1  a violation was found (or a file could not be read)
"""

from __future__ import annotations

import re
import subprocess
import sys

# An ACMM level: "ACMM L6", "acmm l0". Case-insensitive and tolerant of the
# separator, so "ACMM L6", "acmm-l0" and "ACMM  L7" all match.
ACMM_RE = re.compile(r"acmm[-\s]+l\d", re.IGNORECASE)

# An authorship/ownership attribution to an agent: "by the strategist agent",
# "by strategist agent". The word captured as the role is validated below so
# that the generic "by the agent" / "by an agent" -- which this repo's own
# SECURITY.md uses descriptively ("uses automated agents (hive)") -- is not
# treated as a byline.
BY_AGENT_RE = re.compile(r"\bby (?:the |an |a )?(\w+)\s+agent\b", re.IGNORECASE)

# Role words that are articles/determiners, not an agent's name. If the word
# before "agent" is one of these, "by the agent" is a generic reference, not a
# byline attributing authorship to a named agent.
ROLE_STOPWORDS = {"the", "an", "a", "this", "that", "these", "those", "some"}

# Which tracked files to scan. The byline lands in documents, so markdown and
# the other plain-text doc formats cover the regression vector. Scanning the
# whole tree would drag in binaries and generated output; the doc set is where
# a byline is written and reviewed.
SCAN_EXTENSIONS = {".md", ".markdown", ".rst", ".txt"}


def _is_text(data: bytes) -> bool:
    """Return True if a blob looks like a document, not a binary file.

    A NUL byte in the opening chunk means this is not a file a byline would be
    written into (image, archive, compiled artifact), so skip it. This keeps
    the scan from tripping over a binary that happens to contain the bytes.
    """
    return b"\x00" not in data[:4096]


def scan_text(text: str) -> list[tuple[int, str, str]]:
    """Return flagged (line_number, signal, matched_text) for one file's text.

    signal is "acmm-level" or "agent-byline". Empty when the text is clean.
    """
    hits: list[tuple[int, str, str]] = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        for match in ACMM_RE.finditer(line):
            hits.append((lineno, "acmm-level", match.group(0)))
        m = BY_AGENT_RE.search(line)
        if m and m.group(1).lower() not in ROLE_STOPWORDS:
            hits.append((lineno, "agent-byline", m.group(0)))
    return hits


def tracked_text_files() -> list[str]:
    """Return the repo's tracked text files, working-tree content included.

    `git ls-files` lists what is committed; reading each path returns the
    working-tree bytes, so a byline added in the branch but not yet committed is
    still caught -- which is the moment it matters for a gate.
    """
    out = subprocess.run(
        ["git", "ls-files"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return [
        path
        for path in out.splitlines()
        if any(path.endswith(ext) for ext in SCAN_EXTENSIONS)
    ]


def check() -> list[tuple[str, int, str, str]]:
    """Scan every tracked text file; return a flat list of violations.

    Each violation is (path, line_number, signal, matched_text).
    """
    violations: list[tuple[str, int, str, str]] = []
    for path in tracked_text_files():
        try:
            with open(path, "rb") as handle:
                data = handle.read()
        except OSError as exc:  # pragma: no cover - unexpected IO failure
            print(f"warning: could not read {path}: {exc}", file=sys.stderr)
            continue
        if not _is_text(data):
            continue
        text = data.decode("utf-8", errors="replace")
        for lineno, signal, matched in scan_text(text):
            violations.append((path, lineno, signal, matched))
    return violations


def main() -> int:
    violations = check()
    if not violations:
        print("No agent byline or ACMM-level reference found in committed files.")
        return 0

    print(f"Found {len(violations)} file(s) attributing governance to an agent:\n")
    for path, lineno, signal, matched in sorted(violations):
        print(f"  {path}:{lineno}  [{signal}]  {matched!r}")
    print(
        "\nAttribute governance documents to a named human or team owner "
        "(tuna-os/.github#54).",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
