#!/usr/bin/env python3
"""Pin the behavior of check-agent-byline.py.

The gate exists to catch a byline that silently returns, so this suite pins
both sides: the exact regression shapes must fail, and every legitimate mention
of an agent in this repo's own documents must pass. A checker that flags correct
prose gets switched off, and then nothing is checked at all -- so the clean
cases are as important as the dirty ones.

Plain python3, no test framework -- matches how scripts/ is already run in CI.
"""

from __future__ import annotations

import importlib.util
import pathlib
import sys

_src = pathlib.Path(__file__).with_name("check-agent-byline.py")
_spec = importlib.util.spec_from_file_location("check_agent_byline", _src)
check = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(check)


def _signals(text: str) -> set[str]:
    """Return the set of (signal) strings flagged in one piece of text."""
    return {signal for _, signal, _ in check.scan_text(text)}


# (name, text, expect_flagged)
CASES: list[tuple[str, str, bool]] = [
    # --- agent bylines: the regression shapes must be flagged ---
    (
        "maintained by the strategist agent",
        "This roadmap is maintained by the strategist agent.",
        True,
    ),
    (
        "generated by strategist agent at an ACMM level",
        "*Generated by strategist agent at ACMM L6.*",
        True,
    ),
    (
        "footer: maintained ... by the strategist agent",
        "*Maintained as an organization-level planning artifact by the strategist agent.*",
        True,
    ),
    (
        "owned by the architect agent",
        "This policy is owned by the architect agent.",
        True,
    ),
    (
        "no article: by the planner agent",
        "Owned by the planner agent.",
        True,
    ),
    # --- ACMM levels: must be flagged ---
    (
        "ACMM L6 upper",
        "Filed by strategist agent (ACMM L6 -- full mode)",
        True,
    ),
    (
        "acmm l0 lower",
        "running at acmm l0 capacity",
        True,
    ),
    (
        "acmm-l7 hyphen",
        "capability acmm-l7",
        True,
    ),
    # --- legitimate mentions: must NOT be flagged ---
    (
        "human or agent (ROADMAP-INDEX)",
        "nobody -- human or agent -- could see which repos",
        False,
    ),
    (
        "automated agents (hive) (SECURITY.md)",
        "This organization uses automated agents (hive).",
        False,
    ),
    (
        "agent behavior (SECURITY.md)",
        "Reports about agent behavior should go through the private channel.",
        False,
    ),
    (
        "User-Agent header",
        "The hub's edge rejects the default Python-urllib/3.x User-Agent with a 403.",
        False,
    ),
    (
        "agent-authored provenance",
        "hive issues are agent-authored and open to review.",
        False,
    ),
    (
        "agent guide / agent session",
        "any agent with this org checked out picks it up; an agent session does not.",
        False,
    ),
    (
        "generic: by the agent (no named role)",
        "This was done by the agent.",
        False,
    ),
    (
        "generic: by an agent (no named role)",
        "Reviewed by an agent.",
        False,
    ),
    # The critical one: this repo's OWN ROADMAP.md Q4 goal names "an automation
    # agent" as the thing to prevent. It must stay clean.
    (
        "ROADMAP Q4 goal: attributes org policy to an automation agent",
        "No committed file in the portfolio attributes org policy to an "
        "automation agent; every roadmap names a human or team owner",
        False,
    ),
]


def main() -> int:
    failures: list[str] = []
    for name, text, expect_flagged in CASES:
        flagged = bool(_signals(text))
        status = "ok" if flagged == expect_flagged else "FAIL"
        if flagged != expect_flagged:
            failures.append(name)
        print(f"  [{status}] {name} (flagged={flagged}, expected={expect_flagged})")

    # The real repo must pass end to end: every committed text file clean.
    real = check.check()
    if real:
        failures.append("repo self-check")
        for path, lineno, signal, matched in real:
            print(f"  [FAIL] repo file {path}:{lineno} [{signal}] {matched!r}")
    else:
        print("  [ok] repo self-check: no committed file flagged")

    if failures:
        print(f"\n{len(failures)} case(s) failed: {', '.join(failures)}", file=sys.stderr)
        return 1
    print("\nAll cases passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
